---
# 1. Création des identifiants (Login/Password)
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
  namespace: minio
type: Opaque
stringData:
  # Tu peux modifier ces valeurs ici directement
  accesskey: admin
  secretkey: password123

---
# 2. Création du serveur MinIO (Tenant)
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: storage-site
  namespace: minio
spec:
  pools:
    - servers: 1
      volumesPerServer: 1
      size: 20Gi
      storageClassName: longhorn
  mountpath: /export
  credsSecret:
    name: minio-creds-secret
  exposeServices:
    console: true
    minio: true
  # Désactive TLS en interne pour faciliter l'accès via le proxy Rancher
  requestAutoCert: false
