---
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
  namespace: minio
type: Opaque
stringData:
  accesskey: admin
  secretkey: password123

---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: storage-site
  namespace: minio
spec:
  pools:
    - name: pool-0        # <-- Obligatoire : Nom du pool
      servers: 1
      volumesPerServer: 1
      size: 20Gi
      # On définit ici le modèle de volume proprement pour Kubernetes
      volumeClaimTemplate: 
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
  mountpath: /export
  credsSecret:
    name: minio-creds-secret
  exposeServices:
    console: true
    minio: true
  requestAutoCert: false
